-- SQLite
INSERT or replace INTO movie_movie (movieid, title, year, length, genres, rate, poster, plot, trailer)
VALUES  ("tt0499549",
        "Avatar",
        "2009",
        "162",
        "Acción|Aventura|Fantasia|Sci-Fi",
        "7.8",
        "https://m.media-amazon.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_.jpg",
        "Un marine parapléjico enviado a la luna Pandora en una misión única se debate entre seguir sus órdenes y proteger el mundo que siente como su hogar.",
        "https://www.youtube.com/embed/5PSNL1qE6VY" 
        ),
        ("tt0449088",
        "Piratas del Caribe: En el fin del mundo",
        "2007",
        "169",
        "Acción|Aventura|Fantasia",
        "7.1",
        "https://m.media-amazon.com/images/M/MV5BMjIyNjkxNzEyMl5BMl5BanBnXkFtZTYwMjc3MDE3._V1_.jpg",
        "El capitán Barbossa, Will Turner y Elizabeth Swann deberán navegar por los confines del mapa, sortear la traición, encontrar a Jack Sparrow y establecer sus últimas alianzas para una última batalla decisiva.",
        "https://www.youtube.com/embed/HKSZtp_OGHY"
        ),
        ("tt2379713",
        "Spectre",
        "2015",
        "148",
        "Acción|Aventura|Suspenso",
        "6.8",
        "https://m.media-amazon.com/images/M/MV5BOWQ1MDE1NzgtNTQ4OC00ZjliLTllZDAtN2IyOTVmMTc5YjUxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg",
        "Un críptico mensaje del pasado de James Bond le hace seguir la pista para descubrir la existencia de una siniestra organización llamada Spectre.",
        "https://www.youtube.com/embed/ujmoYyEyDP8"
         ),
        ("tt1345836",
        "El caballero oscuro: La leyenda renace(The Dark Knight Rises)",
        "2012",
        "164",
        "Acción|Suspenso",
        "8.4",
        "https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_.jpg",
        "Ocho años después del reinado de anarquía del Joker, Batman, con la ayuda de la enigmática Catwoman, se ve obligado a salir de su exilio para salvar a Gotham City del brutal terrorista guerrillero Bane.",
        "https://www.youtube.com/embed/GokKUqLcvD8"
         ),
        ("tt0401729",
        "John Carter",
        "2012",
        "132",
        "Acción|Aventura|Sci-Fi",
        "6.6",
        "https://m.media-amazon.com/images/M/MV5BMDEwZmIzNjYtNjUwNS00MzgzLWJiOGYtZWMxZGQ5NDcxZjUwXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg",
        "Transportado a Barsoom, un veterano de la Guerra Civil descubre un planeta estéril aparentemente habitado por bárbaros de más de 3 metros de altura y una princesa que necesita desesperadamente un salvador.",
        "https://www.youtube.com/embed/nlvYKl1fjBI"
         ),
        ("tt0413300",
        "Spider-Man 3",
        "2007",
        "139",
        "Acción|Aventura|Romance",
        "6.2",
        "https://m.media-amazon.com/images/M/MV5BYTk3MDljOWQtNGI2My00OTEzLTlhYjQtOTQ4ODM2MzUwY2IwXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg",
        "Un extraño simbionte procedente de otro mundo se une a Peter Parker y le provoca una confusión interior, mientras se enfrenta a nuevos villanos, tentaciones y venganzas.",
        "https://www.youtube.com/embed/e5wUilOeOmg"
         ),
        ("tt0398286",
        "Enredados(Tangled)",
        "2010",
        "100",
        "Aventura|Animación|Comedia|Familiar|Fantasia|Musical|Romance",
        "7.7",
        "https://m.media-amazon.com/images/M/MV5BMTAxNDYxMjg0MjNeQTJeQWpwZ15BbWU3MDcyNTk2OTM@._V1_.jpg",
        "La Rapunzel de pelo largo y mágico ha pasado toda su vida en una torre, pero ahora que un ladrón fugitivo se ha topado con ella, está a punto de descubrir el mundo por primera vez, y quién es realmente.",
        "https://www.youtube.com/embed/ycoY201RTRo"
         ),
        ( "tt2395427",
        "Avengers: Age of Ultron",
        "2015",
        "141",
        "Acción|Aventura|Sci-Fi",
        "7.3",
        "https://m.media-amazon.com/images/M/MV5BMTM4OGJmNWMtOTM4Ni00NTE3LTg3MDItZmQxYjc4N2JhNmUxXkEyXkFqcGdeQXVyNTgzMDMzMTg@._V1_.jpg",
        "Cuando Tony Stark y Bruce Banner intentan lanzar el programa por la paz llamado Ultrón, las cosas salen mal y dependeremos de los héroes más poderosos de la Tierra para frenar el plan del villano Ultrón.",
        "https://www.youtube.com/embed/JAUoeqvedMo"
        ),
        ("tt0417741",
        "Harry Potter y el misterio del príncipe",
        "2009",
        "153",
        "Aventura|Familiar|Fantasia|Misterio",
        "7.6",
        "https://m.media-amazon.com/images/M/MV5BNzU3NDg4NTAyNV5BMl5BanBnXkFtZTcwOTg2ODg1Mg@@._V1_.jpg",
        "Cuando Harry Potter empieza su sexto año en Hogwarts, descubre un viejo libro marcado como propiedad del príncipe mestizo y comienza a aprender más sobre el oscuro pasado de Lord Voldemort",
        "https://www.youtube.com/embed/CHiGk9bEht8"
        ),
        (   "tt2975590",
        "Batman v Superman. El amanecer de la justicia",
        "2016",
        "151",
        "Acción|Aventura|Sci-Fi",
        "6.5",
        "https://m.media-amazon.com/images/M/MV5BYThjYzcyYzItNTVjNy00NDk0LTgwMWQtYjMwNmNlNWJhMzMyXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg",
        "Ante el temor de que las acciones de Superman queden fuera de supervisión, Batman se enfrenta al Hombre de Acero, mientras el mundo se pregunta qué tipo de héroe realmente necesita.",
        "https://www.youtube.com/embed/IwfUnkBfdZ4"
      ),
        (  "tt0348150",
        "Superman Returns: El regreso",
        "2006",
        "154",
        "Acción|Aventura|Sci-Fi",
        "6",
        "https://m.media-amazon.com/images/M/MV5BNzY2ZDQ2MTctYzlhOC00MWJhLTgxMmItMDgzNDQwMDdhOWI2XkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_.jpg",
        "Superman reaparece después de una larga ausencia, pero es desafiado por un viejo enemigo que utiliza la tecnología kriptoniana para dominar el mundo.",
        "https://www.youtube.com/embed/bRqAUqAFhNw" 
      ),
        (        "tt0830515",
        "Quantum of Solace",
        "2008",
        "106",
        "Acción|Aventura",
        "6.6",
        "https://m.media-amazon.com/images/M/MV5BMjZiYTUzMzktZWI5Yy00Mzk4LWFlMDgtYjRmNWU0Mzc0MzNiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg",
        "James Bond se sumerge en el misterio mientras intenta impedir que una organización misteriosa elimine el recurso más valioso de un país.",
        "https://www.youtube.com/embed/BBqYaFEWBxI"
      ),
        ("tt0383574",
        "Piratas del Caribe: El cofre del hombre muerto",
        "2006",
        "151",
        "Acción|Aventura|Fantasia",
        "7.3",
        "https://m.media-amazon.com/images/M/MV5BMTcwODc1MTMxM15BMl5BanBnXkFtZTYwMDg1NzY3._V1_.jpg",
        "Jack Sparrow se apresura a recuperar el corazón de Davy Jones para evitar esclavizar su alma al servicio de Jones, mientras otros amigos y enemigos buscan también el corazón para sus propios fines.",
        "https://www.youtube.com/embed/SNA-Ezahmok"
      ),
        ("tt0770828",
        "El hombre de acero (Man of Steel)",
        "2013",
        "143",
        "Acción|Aventura|Fantasia|Sci-Fi",
        "7.1",
        "https://m.media-amazon.com/images/M/MV5BMTk5ODk1NDkxMF5BMl5BanBnXkFtZTcwNTA5OTY0OQ@@._V1_.jpg",
        "An alien child is evacuated from his dying world and sent to Earth to live among humans. His peace is threatened, when survivors of his home planet invade Earth.",
        "https://www.youtube.com/embed/T6DJcgm3wNY"
      ),
        ("tt0499448",
        "Las crónicas de Narnia: El príncipe Caspian",
        "2008",
        "150",
        "Acción|Aventura|Familiar|Fantasia",
        "6.5",
        "https://m.media-amazon.com/images/M/MV5BMTIwOTA4NTE4Ml5BMl5BanBnXkFtZTcwOTI2NTg1MQ@@._V1_.jpg",
        "Los hermanos Pevensie regresan a Narnia, donde son reclutados de nuevo para ayudar a proteger al reino de un rey malvado y restaurar al heredero legítimo del trono, el príncipe Caspian.",
        "https://www.youtube.com/embed/zZfDS5eu7fA"
      ),
        ("tt0848228",
        "The Avengers",
        "2012",
        "143",
        "Acción|Aventura|Sci-Fi",
        "8",
        "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
        "Los héroes más poderosos de la Tierra deben unirse y aprender a luchar en equipo si quieren evitar que Loki y su ejército alienígena esclavicen a la humanidad.",
        "https://www.youtube.com/embed/eOrNdBpGMv8"
      ),
        ("tt1298650",
        "Piratas del Caribe: En mareas misteriosas",
        "2011",
        "136",
        "Acción|Aventura|Fantasia",
        "6.6",
        "https://m.media-amazon.com/images/M/MV5BMjE5MjkwODI3Nl5BMl5BanBnXkFtZTcwNjcwMDk4NA@@._V1_.jpg",
        "Jack Sparrow y Barbossa se embarcan en una búsqueda para encontrar la escurridiza fuente de la juventud, solo para descubrir que Barbanegra y su hija también están tras ella.",
        "https://www.youtube.com/embed/0BXCVe8Yww4"
      ),
        ("tt1409024",
        "Men in Black 3",
        "2012",
        "106",
        "Acción|Aventura|Comedia|Familiar|Fantasia|Sci-Fi",
        "6.8",
        "https://m.media-amazon.com/images/M/MV5BMTU2NTYxODcwMF5BMl5BanBnXkFtZTcwNDk1NDY0Nw@@._V1_.jpg",
        "El agente J viaja en el tiempo a los inicios del MIB en 1969 para evitar que un alienígena asesine a su amigo el agente K y cambie la historia.",
        "https://www.youtube.com/embed/IyaFEBI_L24"
      ),
        ("tt2310332",
        "El hobbit: La batalla de los cinco ejércitos",
        "2014",
        "144",
        "Aventura|Fantasia",
        "7.4",
        "https://m.media-amazon.com/images/M/MV5BODAzMDgxMDc1MF5BMl5BanBnXkFtZTgwMTI0OTAzMjE@._V1_.jpg",
        "Bilbo y compañía se ven obligados a entrar en guerra contra una serie de combatientes y evitar que la Montaña Solitaria caiga en manos de una creciente oscuridad.",
        "https://www.youtube.com/embed/iVAgTiBrrDA"
      ),
        ( "tt0948470",
        "The Amazing Spider-Man",
        "2012",
        "136",
        "Acción|Aventura|Fantasia",
        "6.9",
        "https://m.media-amazon.com/images/M/MV5BMjMyOTM4MDMxNV5BMl5BanBnXkFtZTcwNjIyNzExOA@@._V1_.jpg",
        "Después de que Peter Parker sea mordido por una araña genéticamente alterada, adquiere poderes arácnidos y se aventura a salvar la ciudad de las maquinaciones de un misterioso enemigo reptiliano, el Lagarto.",
        "https://www.youtube.com/embed/-tnxzJ0SSOw"
      ),
        ( "tt0955308",
        "Robin Hood",
        "2010",
        "140",
        "Acción|Aventura|Drama|Historia",
        "6.6",
        "https://m.media-amazon.com/images/M/MV5BMTM5NzcwMzEwOF5BMl5BanBnXkFtZTcwNjg5MTgwMw@@._V1_.jpg",
        "En la Inglaterra del siglo XII, Robin y su banda se enfrentan a la corrupción en su localidad y lideran una rebelión contra la corona que cambiará el equilibrio de poder para siempre.",
        "https://www.youtube.com/embed/fQ6zXDSgwIY" 
      ),
        ("tt1170358",
        "El hobbit: La desolación de Smaug",
        "2013",
        "161",
        "Aventura|Fantasia",
        "7.8",
        "https://m.media-amazon.com/images/M/MV5BMzU0NDY0NDEzNV5BMl5BanBnXkFtZTgwOTIxNDU1MDE@._V1_.jpg",
        "Los enanos, junto con Bilbo Bolsón y Gandalf el Gris, continúan en su misión para reclamar Erebor, su hogar, de Smaug. Bilbo Bolsón posee un misterioso y mágico anillo.",
        "https://www.youtube.com/embed/fnaojlfdUbs" 
      ),
        ( "tt0385752",
        "La brújula dorada",
        "2007",
        "113",
        "Aventura|Familia|Fantasia",
        "6.1",
        "https://m.media-amazon.com/images/M/MV5BMTM2NDkxMjQxMV5BMl5BanBnXkFtZTYwNTMxMDM4._V1_.jpg",
        "En un universo paralelo, la joven Lyra Belacqua viaja al lejano norte para salvar a su mejor amigo y a otros niños secuestrados de los terribles experimentos de una misteriosa organización.",
        "https://www.youtube.com/embed/LHYoOGfBObU
      )
/*INSERT or replace INTO movie_movie (movieid, title, year, length, genres, rate, poster, plot, trailer)
VALUES ()*/